# Generated by Django 2.1.7 on 2019-03-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0006_auto_20190324_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='rating',
        ),
    ]
