# Generated by Django 2.1.7 on 2019-03-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0008_restaurante_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='info',
            field=models.TextField(default='Sin informacion', max_length=300),
        ),
    ]
